version: '3'
services:
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3010:3000"
    depends_on:
      - db
    environment:
      - SMTP_PORT=2525
      - FRONTEND=http://localhost:3000
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
