name: Ruby on Rails CI

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
      ports:
        - 5432:5432
      env:
        POSTGRES_DB: 'hitchlog_api_test'
        POSTGRES_USER: 'hitchlog_api'
        POSTGRES_PASSWORD: 'password'
    env:
      RAILS_ENV: test
      DB_PASSWORD: password
      DB_USER: hitchlog_api
      
    steps:
    - uses: actions/checkout@v3
    - name: Install ruby and gems
      uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
