name: "Ruby on Rails CI"

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: 'hitchlog_api_test'
          POSTGRES_USER: 'hitchlog_api'
          POSTGRES_PASSWORD: 'password'
    env:
      RAILS_ENV: test
      DB_PASSWORD: password
      DB_USER: hitchlog_api
      
    steps:
    - run: npm install -g pnpm
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install required apt packages
      run: |
        sudo apt-get -y install libpq-dev
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
    - name: Setup cache key and directory for gems cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-use-ruby-${{ hashFiles('**/Gemfile.lock') }}
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - uses: actions/checkout@v3
    - name: Set up database schema
      run: bundle exec rake db:schema:load
    - name: Run tests
      run: bundle exec rake
